site_name: DisSModel
site_url: https://profsergiocosta.github.io/dissmodel/
repo_url: https://github.com/profsergiocosta/dissmodel
repo_name: GitHub
theme:
  name: material
  language: pt

markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Início: index.md
  - Módulos:
    - Core: modules/core.md
    - Visualization: modules/visualization.md
  - Exemplos:
      - Autômatos Celulares:
          - Introdução: examples/CA/index.md
          - Game of Life: examples/CA/game_of_life.md
          - Modelo de Queimada: examples/CA/fire_model.md