site_name: DisSModel
site_url: https://profsergiocosta.github.io/dissmodel/
repo_url: https://github.com/profsergiocosta/dissmodel
repo_name: GitHub
theme:
  name: material
  language: pt
nav:
  - Início: index.md
  - Exemplos:
      - Autômatos Celulares:
          - Introdução: examples/CA/index.md
          - Game of Life: examples/CA/game_of_life.md
          - Modelo de Queimada: examples/CA/fire_model.md