site_name: DisSModel
site_url: https://lambdageo.github.io/dissmodel/
repo_url: https://github.com/lambdageo/dissmodel
repo_name: dissmodel

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true
  - mkdocs-jupyter:
      include: ["*.ipynb"]

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: green


markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Why DisSModel?: why_dissmodel.md
  - Examples: examples.md



  - API Reference:
    - Core: api/core.md
    - Geo:
      - Overview: api/geo/index.md
      - Vector: api/geo/vector.md
      - Raster: api/geo/raster.md
    - Executor:
      - Overview: api/executor/index.md
      - Schemas: api/executor/schemas.md
      - CLI: api/executor/cli.md
      - Testing: api/executor/testing.md
    - IO: api/io/index.md
    - Visualization: api/visualization.md
